### PR TITLE
MAC authentication for the Babel routing protocol

### PR DESCRIPTION
**Pull request by MisterDA**
This PR:
- rebases the current hmac branch against babeld 1.9.2;
  this can be undone if unwanted.
- changes minor things to the hmac code;
- changes the `no_hmac_verify` to `hmac-verify` because it was inconsistent with other babeld options and the Information Model;
- always uses constants from the reference implementation for key and digest size;
  this is nice because blake2s sizes were wrong.
- optimises a bit our custom hmac-sha256 implementation.

I have tested that my rewrite of hmac-sha256 is compatible with the current hmac implementation and with the reference hmac-sha256 implementation. Note that the reference hmac-sha256 implementation weights up babeld by 32Ko - 36Ko (with `-Os -g`). Lower bound is with LTO. Patch for reference implementation: 906b38eb3bca2dcc.

### CODE REVIEW

**Comment by MisterDA** [comment]
I would appreciate a review of 6891559, the rewrite of the preparse phase.

**Comment by tohojo** [comment]
@MisterDA FYI the configuration parser didn't permit me to omit the 'use' value in MAC key definitions. Fixed it with this:

```patch
diff --git a/configuration.c b/configuration.c
index 6068d8c8c357..a5ade9846f05 100644
--- a/configuration.c
+++ b/configuration.c
@@ -924,7 +924,9 @@ parse_key(int c, gnc_t gnc, void *closure, struct key **key_return)
     token = token2 = NULL;
 
     c_tmp = skip_whitespace(c, gnc, closure);
-    if(c_tmp != '\n') {
+    if(c_tmp == '\n') {
+        goto fini;
+    } else {
         c = skip_eol(c_tmp, gnc, closure);
         if(c != -2)
             goto fini;
```

**Comment by jech** [comment]
I'm a little confused.  An interface is associated with a key "superset", which is associated with a set of key sets, each of which contains multiple keys.

What is the reason for this double indirection?  I'd expect an interface to be associated with a single keyset, which can then be edited at will.

**Comment by MisterDA** [comment]
> What is the reason for this double indirection? I'd expect an interface
> to be associated with a single keyset, which can then be edited at will.

The intent is to allow more flexibility for the users. Suppose all
interfaces should share the same set of keys. With key super sets, a
single key set could be attached to each interface. Then, rotating
keys is simply a matter of editing that key set. Without super key
sets, we must iterate over all interfaces, possibly introducing delays
between changes on each interface key set.

The double indirection also allows complex key deployment scenarios,
with "split networks" where sets of interfaces could share sets of
keys.

Note that (altought I think that's less of a concern), the Babel
Information Model uses the double indirection.

I also think that using so-called default key sets and command macros
can help masking the "advanced features".

**Comment by jech** [comment]
Thanks, Antonin.  I've merged the part that fixes the protocol.  I did not merge the part that deals with multiple keys and key rotation, since I think you've overengineered it somewhat — more thought is needed.

**Pull request closed without merging**
