### PR TITLE
Allow setting preferred source in routes per interface and ip address

### PR DESCRIPTION
**Pull request by killianlufau**
This replaces https://github.com/jech/babeld/pull/18 and adds the ability to filter by address while keeping the feature of filtering by interface

### CODE REVIEW

**Comment by jech** [comment]
I'm not sure I understand what's going on in rule.c.

The current code allows setting the destination table in an install filter; it appears that you remove this functionality.  Is that correct?

If that's the case, then this needs to be discussed on the mailing list, and you'll need to split the patch into two (one that removes the existing functionality, and one that adds the new functionality).

**Comment by killianlufau** [comment]
This PR does not remove existing functionality. We move some code from rule.c to disambiguation.c to avoid calling install_filter twice.
In other words, the beginning of find_table is moved to the only place this function is used.

**Comment by killianlufau** [comment]
@jech I split the PR in two commits, separating the refactoring part and the new feature to set pref-src through install filters

**Comment by killianlufau** [comment]
@jech what do you think? I'll start working on the documentation if everything is okay for you !

**Comment by killianlufau** [comment]
@jech,

Thanks for your comment on https://github.com/jech/babeld/pull/18, 
In reply to this,
- I fixed the compilation and applied the changes you wanted.

- In regards to "on this subject — should the check for m < INFINITY be here or in kernel_route? I don't mind either way, but I'm wondering.", 
I think it's okay to let it here, plus if we put it in kernel_route we should carry the value of the return of `install_filter' and `filter_result` as well.

**Comment by jech** [comment]
Looks good to me.  Applied but not pushed yet.

**Comment by jech** [comment]
Note that this has pretty horrible error behaviour — if the pref-src address doesn't correspond to a locally assigned IP address, then route installation fails with EINVAL.  Babeld will recover, but it will try again slightly later.

Pushed, thanks Killian.

**Pull request closed without merging**
