### PR TITLE
Micro patches

### PR DESCRIPTION
**Pull request by MisterDA**
Also please see: https://github.com/jech/babeld/blob/0835d5d894ea016ab7b81562466cade2c51a12d4/kernel_netlink.c#L399 
Either there’s a missing `else`, or this block should better be on a new line.

### CODE REVIEW

**Comment by MisterDA** [comment]
There will be a NULL dereference in `rt_cmp` https://github.com/jech/babeld/blob/0835d5d894ea016ab7b81562466cade2c51a12d4/disambiguation.c#L52-L55 if `rt2` is… null.
This can happen if the allocation fails in `min_conflict`:
https://github.com/jech/babeld/blob/0835d5d894ea016ab7b81562466cade2c51a12d4/disambiguation.c#L152-L155
which is called multiple times such as here:
https://github.com/jech/babeld/blob/0835d5d894ea016ab7b81562466cade2c51a12d4/disambiguation.c#L311

I’ll admit that it’s nearly impossible. A chance of 1 over 42 to the power of [a russian song](https://www.youtube.com/watch?v=6vSjrAsn1Io). Unless a NULL route gets in here by another way…

**Comment by MisterDA** [comment]
With the last 7 commits, allocated memory is freed just before babeld
exits. On my local test environment, Valgrind states that:

> All heap blocks were freed -- no leaks are possible

which is nice, because new code can be tested for leaks without the
noise.

**Comment by jech** [comment]
I've just pushed the ones that feel useful and safe for 1.9.2.  You may want to rebase your branch. 
 Please let me know if there are any patches left that you feel should be in 1.9.2.

**Comment by MisterDA** [comment]
Ok, thanks! I do consider that two commits should be included for 1.9.2, for posterity if it’s the last version in the 1.9 series.

- Fix signed/unsigned comparison and priting warnings. 5ab6f4c 
- Switch from usleep to nanosleep. 2b4e08e
  > POSIX.1-2001  declares this function obsolete; use nanosleep(2) instead.  POSIX.1-2008 removes  the  specification  of usleep().
  > `man usleep`

The remaining of the commits removes dead code, fixes style issues, and makes babeld pass the terrifying Valgrind test.

**Comment by jech** [comment]
> * Fix signed/unsigned comparison and priting warnings. 5ab6f4c

    @@ -261,7 +261,7 @@ filter_address(struct kernel_addr *addr, void *data) {
         int maxroutes = *(int *)args[0];
         struct kernel_route *routes = (struct kernel_route*)args[1];
         int *found = (int *)args[2];
    -    int ifindex = *(int*)args[3];
    +    unsigned ifindex = *(unsigned*)args[3];
         int ll = args[4] ? !!*(int*)args[4] : 0;
         struct kernel_route *route = NULL;

This looks wrong to me.  You take an int*, cast it into void*, then
reinterpret it as an unsigned*.

> * Switch from usleep to nanosleep. 2b4e08e 

Why the messy global variable?  Why not define a new function in util.c
that does the right thing?

-- Juliusz

**Comment by MisterDA** [comment]
> This looks wrong to me.  You take an int*, cast it into void*, then reinterpret it as an unsigned*.

I’ll look into that.

>>  * Switch from usleep to nanosleep. 2b4e08e
>
> Why the messy global variable?  Why not define a new function in `util.c` that does the right thing?

'cause we’d have to find a name…
Let’s see. `sleep`, `usleep`, and `nanosleep` are taken. How about (untested draft):

```c
void
siesta(int usec) {
    struct timespec sleeper = { /* in the valley */
        .tv_sec = 0,
        .tv_nsec = roughly(usec * 1000);
    };
    nanosleep(&sleeper, NULL);
}
```

Does it need error handling in case `nanosleep` is interrupted by a signal?

**Comment by jech** [comment]
> 'cause we’d have to find a name…

nsleep?  nap?

> Does it need error handling in case nanosleep is interrupted by a signal?

It need not -- the only case where it matters is handled in select.  For
completeness, I think your function should return the result of nanosleep.

I still don't understand why this patch is needed for 1.9.2, though.  What
issue does it fix?

-- Juliusz

**Comment by MisterDA** [comment]
> For completeness, I think your function should return the result of nanosleep.

Done. 045be19

> I still don't understand why this patch is needed for 1.9.2, though.  What issue does it fix?

It’s using a deprecated function, obsolete since 2001 and unspecified since 2008. babeld should not use unspecified functions.

> This looks wrong to me.  You take an `int*`, cast it into `void*`, then reinterpret it as an `unsigned*`.

Good catch. We’re dealing with a `struct ifaddrm` in the end, so the `ifindex` should be an `unsigned int`. Should be fixed now in 2c43c42.

**Comment by jech** [comment]
>     I still don't understand why this patch is needed for 1.9.2, though. What
>     issue does it fix?

> It’s using a deprecated function, obsolete since 2001 and unspecified since
> 2008. babeld should not use unspecified functions.

It's not portable software anyhow, it depends on netlink or BSD routing sockets.

I won't put it in 1.9.2.  I might reconsider for 1.10.

-- Juliusz

**Comment by MisterDA** [comment]
> I won't put it in 1.9.2.

Bouh!

> I might reconsider for 1.10.

How long after the heat death of the universe will that be?

**Comment by jech** [comment]
> Remove useless checks.

This patch just removes checks that are redundant.  I prefer to keep them, I like defensive coding; the performance penalty should be negligible.

> Inline last_interface() into add_interface().

What problem are you trying to solve?  Rejected.

> Reformat kernel_netlink.c.

Applied, but please don't do that in the future.  Gratuitious cosmetic changes are a common way to introduce bugs.

> Reformat kernel_socket.c.

Rejected, unless you can confirm that you've carefully tested your change.

> Free old_if when calling kernel_setup(0).

Applied, thanks.

> Mark old_if array as static.

Applied, thanks.

> Fix signed/unsigned comparison and priting warnings.
> Use unsigned int for interface indexes.

Rejected.  These are the kind of cosmetic changes that is likely to introduce subtle bugs.

> Remove unused ifindex parameter.

Rejected.  We try to carry both ifname and ifindex throughout the code.

> Use %p to print pointers.

Rejected.  As far as I recall `%p` prints data in an implementation-defined format.

> Switch from usleep to nanosleep.

The word *siesta* is not a verb.  Please call this function `nap` or `doze`.  Rejected for now.

> gitattributes: ignore gitmodules, cpp mode for diff.

Rejected.  There's no `.gitmodules` in this branch.  As to the rest, please explain what actual problem it tries to solve.

> Functions that take no parameter should be void.

This is a workaround for a misfeature of C86 that has been fixed in C11.  Rejected.

> Free receive_buffer.
> Free filters.
> Free interfaces.
> Free neighbours.
> Free xroutes.
> Free sources.

Are you proting `babeld` to a system that doesn't have a proper process abstraction?  Please explain what problem you are trying to solve.

> Release memory at exit only when testing with Valgrind.

Having different code paths depending on whether a debugger is attached is a sure way to end up with undebuggable code.  Rejected.

> generate_version: get git version and tag from anywhere.

I have no idea what this does.  Please resubmit with a message explaining what particular problem you're trying to solve.

> Remove dead increment.

Rejected.  `current_attribute` always points past the last attribute, and your change breaks this invariant.  What problem are you trying to solve?

> Prevent unspecified behaviour when zeroing union.
> Remove unneeded call to memset.
> Remove declaration of undefined function.

Applied.

> Don't memcpy channels if length is 0.

Applied.  Did you check that this is the only occurrence of `memcpy(NULL, 0)`?

> Change pseudo-bools type from int to char.

Applied.

> Prevent use of uninitialized token.

Why do you believe `token` can be used unitalised?  As far as I can tell, it's only uninitialised if `c < -1`.  If the patch is there to shut up whatever linter you're using on my code, the commit message should say so.

> pid_t is a signed integer type.

Yes, but `getpid` is documented to always return a positive value.

**Comment by MisterDA** [comment]
Thanks for the comments!
I just need to discuss the issue below before I submit new, and better defended commits.

> > Free receive_buffer.
> > Free filters.
> > Free interfaces.
> > Free neighbours.
> > Free xroutes.
> > Free sources.
> 
> Are you porting `babeld` to a system that doesn't have a proper process abstraction? Please explain what problem you are trying to solve.
> 
> > Release memory at exit only when testing with Valgrind.
> 
> Having different code paths depending on whether a debugger is attached is a sure way to end up with undebuggable code. Rejected.

I agree that there should be no need for free'ing data that lives throughout the program execution, since the OS discards the memory when the program exits. However, if you run babeld under Valgrind or under a sanitizer, as babeld doesn't free the memory, the data-structures will show up as memory leaks. It is cumbersome to exclude from the report all the "expected" leaks to find potentially newly introduced leaks, so I’ve decided to add functions to free the data-structures. However, being aware that the OS eventually takes care of that for us, I thought that they could be called only if we were explicitly testing for memory leaks (note: using `HAVE_VALGRIND` here doesn't make sense if a sanitizer is used instead, so it's not a great idea anyway). I see how diverging code paths can be a problem, however I don't see a clean solution for having the best of both worlds.

**Comment by jech** [comment]
I still don't see what actual (as opposed to potential) problem you are trying to solve.

Releasing all data at shutdown was necessary on older memory debuggers, such as *Electric Fence*, that couldn't distinguish between reachable but unreleased data and actual memory leaks.  Modern memory debuggers don't have this issue — *valgrind* prints a summary report that clearly distinguishes between reachable data and garbage.

**Comment by MisterDA** [comment]
> valgrind prints a summary report that clearly distinguishes between reachable data and garbage.

I guess I missed that, it effectively voids my concerns. I’ll drop the related commits. Thanks!

**Pull request closed without merging**
