### PR TITLE
Fix txcost for wireguard links

### PR DESCRIPTION
**Pull request by jrb0001**

### CODE REVIEW

**Comment by zorun** [comment]
@jrb0001 could you describe the problem you are facing?  This looks like the wrong place for such a change.

Have a look at the man page, `type tunnel` is probably what you want on your wireguard interfaces.  If babeld does not detect a wireguard interface as a tunnel interface by default, this should be fixed.

**Comment by jrb0001** [comment]
The problem is that txcost is 65535 and thus babeld is installing all routes as unreachable. `type tunnel` didn't do anything.

**Comment by zorun** [comment]
This simply means that babeld cannot communicate bidirectionally with its peer across the tunnel.

Make sure that your wireguard interfaces have link-local addresses, that fe80::/10 is allowed by wireguard in both directions, and that you don't have a firewall blocking babel packets.  Post on the mailing list http://lists.alioth.debian.org/cgi-bin/mailman/listinfo/babel-users if you need further help.

**Comment by jrb0001** [comment]
Bidirectional communication is possible. I can ping and tcpdump shows the babeld packets from the local host as well as those from the remote host. I think the problem might be that the multicast packets aren't looped back and thus babeld fails to determine the txcost. With my changes, everything works fine.

**Comment by zorun** [comment]
Did you check that your firewall allows Babel packets?  tcpdump shows packets **before** they are dropped by the firewall, it can be misleading.

If the firewall is not the issue, please provide a tcpdump capture containing the Babel packets only (the pcap file, not a text output).  It sounds like something strange related to link-local addresses (or lack thereof).

**Comment by jrb0001** [comment]
I have attached a tcpdump capture of the wireguard interface on one of the hosts. I had to wrap it in a .zip because GitHub refuses other file extensions. There is no firewall so that shouldn't be an issue.
[babeld.pcap.zip](https://github.com/jech/babeld/files/1272262/babeld.pcap.zip)

**Comment by zorun** [comment]
Everything seems fine in the trace.  So, if your code makes a difference, it means that babeld rejects the IHU because it thinks it's meant for another node. See here: https://github.com/jech/babeld/blob/master/interface.c#L510

Maybe the kernel thinks that your interface is down somehow? What flags can you see in `ip link show` and can you try to turn the wireguard interface down and up? Also, did you use `link-detect` in the babeld config?

Other than that, I'm running out of ideas, let's wait for @jech :)

**Comment by jrb0001** [comment]
`wg-host-2: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1420 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000` so it should be up. I didn't use `link-detect` unless that's on by default.

**Comment by tohojo** [comment]
Erm, wireguard doesn't forward multicast traffic at all AFAIK. Are you sure that the Babel packets are going through the tunnel?

A workaround is to run a gretap point-to-point tunnel on top of wireguard and run babel on that...

**Comment by jrb0001** [comment]
I configured it to forward `::/0` which should include multicast AFAIK. It doesn't matter if wireguard treats multicast as unicast because it is a point to point link anyway. If you check the tcpdump file from above, you can see that the babeld packets are going through the tunnel successfully.

 While gre over wireguard would probably work, it would reduce the MTU even more without any real benefit.

**Comment by jech** [comment]
Can you confirm that babeld is detecting the interface's link-local address of the wireguard interface correctly?  Please run babeld with the `-g 33123` flag, then do:

    telnet ::0 33123
    dump
    quit

and post the output.

**Comment by jrb0001** [comment]
```
root@host-1:~# telnet ::0 33123
Trying ::...
Connected to ::0.
Escape character is '^]'.
BABEL 1.0
version babeld-1.8.0-15-g6c02c3c
host host-1
my-id 5c:46:db:2f:a7:01:f9:b5
ok
dump
add interface wg-host-2 up true ipv6 fe80::7fbe
add neighbour 55afd1779d20 address fe80::7fbe if wg-host-2 reach ffff rxcost 96 txcost 96 rtt 1.119 rttcost 1 cost 97
add xroute fd42:5d71:219::54a4/128-::/0 prefix fd42:5d71:219::54a4/128 from ::/0 metric 1
add route 55afd1779e30 prefix fd42:5d71:219::7fbe/128 from ::/0 installed yes id a8:17:c6:21:9d:83:54:5b metric 98 refmetric 1 via fe80::7fbe if wg-host-2
ok
quit
Connection closed by foreign host.
```
Keep in mind that this is with my changes applied.

```
root@host-1:~# ip -6 addr show wg-host-2
12: wg-host-2: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1420 state UNKNOWN qlen 1000
    inet6 fe80::54a4 peer fe80::7fbe/128 scope link 
       valid_lft forever preferred_lft forever
```
and
```
root@host-2:~# ip -6 addr show wg-host-1
4: wg-host-1: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1420 state UNKNOWN qlen 1000
    inet6 fe80::7fbe peer fe80::54a4/128 scope link 
       valid_lft forever preferred_lft forever
```
show all addresses on both sides of the tunnel.

**Comment by jech** [comment]
> add interface wg-host-2 up true ipv6 fe80::7fbe
> add neighbour 55afd1779d20 address fe80::7fbe if wg-host-2 reach ffff rxcost 9

[...]

> root@host-1:~# ip -6 addr show wg-host-2
> 12: wg-host-2: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1420 state UNKNOWN qlen 1000
>     inet6 fe80::54a4 peer fe80::7fbe/128 scope link 
>        valid_lft forever preferred_lft forever

> root@host-2:~# ip -6 addr show wg-host-1
> 4: wg-host-1: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1420 state UNKNOWN qlen 1000
>     inet6 fe80::7fbe peer fe80::54a4/128 scope link 
>        valid_lft forever preferred_lft forever

You've got the same link-local address on both interfaces, so Babel is
discarding Hellos from the neighbour since it thinks it's speaking to
itself.

-- Juliusz

**Comment by boutier** [comment]
> > add interface wg-host-2 up true ipv6 fe80::7fbe

> > root@host-1:~# ip -6 addr show wg-host-2
> > inet6 fe80::54a4 peer fe80::7fbe/128 scope link 

> > root@host-2:~# ip -6 addr show wg-host-1
> > inet6 fe80::7fbe peer fe80::54a4/128 scope link 

> You've got the same link-local address on both interfaces

I don't think so…

host1's address is fe80::54a4
host2's address is fe80::7fbe

But it seems that Babel netlink's interface interprets the "peer fe80::7fbe" part
as the interface's link-local address.

Matthieu

**Comment by jech** [comment]
You're right.  So it's either a bug in babeld, or a bug in wireguard's netlink interface.  Unfortunately, I don't have time to find out which right now.

**Comment by boutier** [comment]
> You're right. So it's either a bug in babeld, or a bug in wireguard's netlink interface. Unfortunately, I don't have time to find out which right now

The ip command correctly parse the message, so it should be a bug in Babel.

[...] looking at iproute2/ip/ipaddress.c

  search " peer %s/%d "

In this case, we have both IFA_LOCAL and IFA_ADDRESS messages... so it should be sufficient to ignore IFA_ADDRESS when we have IFA_LOCAL.

So, in parse_addr_rta, I would propose either to

  1. just return once we have found one address:

1338 -          break;
1338 +          return 0;

or
  2. to put a "has_address" flag:

+   int has_addr = 0;

    while(RTA_OK(rta, len) && !has_addr) {
        switch(rta->rta_type) {
-       case IFA_LOCAL:
        case IFA_ADDRESS:
+       case IFA_LOCAL:
            if(has_addr)
                break;
            has_addr = 1;
            switch(addr->ifa_family) {

Preference?  (untested)

Matthieu

**Comment by jrb0001** [comment]
https://github.com/jech/babeld/compare/master...jrb0001:parse_addr_rta seems to fix it although I am not sure why.

**Comment by boutier** [comment]
> I am not sure why.

Thank's for testing.  The reason is that when an interface has an address like "X peer Y", netlink sends X as an "IFA_LOCAL" TLV and Y as an "IFA_ADDRESS" TLV, while both are in the same "address" message.  Because the first TLV which appears is "IFA_LOCAL", the current babel code was overriding the address when the "IFA_ADDRESS" TLV was parsed.  This modification essentially says: stop, we have the address we were looking for (X).

Matthieu

**Comment by zorun** [comment]
Nice debugging!

@jrb0001  Using /128 for link-local addresses is highly unusual, do you have a particular reason not to use a /64?

**Comment by jrb0001** [comment]
@zorun I can save address space that way :) But to be honest there is no reason. The only difference is that the point to point link is easier to spot that way.

**Comment by boutier** [comment]
@jrb0001 Could you please test this patch:

    https://github.com/boutier/babeld/commit/9be552feda7fafb0d70b7ba552ff6f72c5b4b38e

Contrary to the (ad-hoc) previous one, it does not rely on the parsing order of the TLVs.

@zorun Yes, a good teamwork. :-)

**Comment by jrb0001** [comment]
@boutier Looks like I hit an issue on the first try but I can't reproduce it:
```
My id 10:54:a6:bc:9d:97:30:59 seqno 11072
Neighbour fe80::7fbe dev wg-host-2 reach ffff rxcost 96 txcost 65535 rtt 0.888 rttcost 0 chan -2.
fd42:5d71:219::54a4/128 metric 1 (exported)
fd42:5d71:219::54a4/128 metric 65535 (65535) refmetric 65535 id 74:94:8a:12:f8:2c:ea:cc seqno 49871 chan (255) age 29 via wg-host-2 neigh fe80::7fbe (feasible)
fd42:5d71:219::7fbe/128 metric 65535 (65535) refmetric 1 id 80:88:af:81:41:80:2b:33 seqno 1553 age 11 via wg-host-2 neigh fe80::7fbe (installed)
```

**Comment by boutier** [comment]
> @boutier Looks like I hit an issue on the first try but I can't reproduce it:

I don't think there is any issue here.  At least the patch makes its job (addresses are well parsed).

> My id 10:54:a6:bc:9d:97:30:59 seqno 11072
> Neighbour fe80::7fbe dev wg-host-2 reach ffff rxcost 96 txcost 65535 rtt 0.888 rttcost 0 chan -2.
> fd42:5d71:219::54a4/128 metric 1 (exported)
> fd42:5d71:219::54a4/128 metric 65535 (65535) refmetric 65535 id 74:94:8a:12:f8:2c:ea:cc seqno 49871 chan (255) age 29 via wg-host-2 neigh fe80::7fbe (feasible)

This looks like something weird, but it's just a retraction, and "retractions are always feasible".

> fd42:5d71:219::7fbe/128 metric 65535 (65535) refmetric 1 id 80:88:af:81:41:80:2b:33 seqno 1553 age 11 via wg-host-2 neigh fe80::7fbe (installed)

This is also a retracted route: it's installed (as unreachable) to avoid routing loops.  The unreachable route is only kept for a few seconds (after what the network is consider to have purged the retracted route).

Matthieu

**Comment by jech** [comment]
Believed to be fixed in 98ce829827e8c349830bcb3375f9c3ff4107b60f.  Please reopen if not.

**Pull request closed without merging**
