### PR TITLE
Remove disambiguation

### PR DESCRIPTION
**Pull request by MisterDA**
This is an attempt at removing the disambiguation code, and the kernel rules.
I may have missed some codectomy or messed up the stitches.

### CODE REVIEW

**Comment by adschm** [comment]
@fblaese FYI. Your e-mail about high CPU is mentioned in the first commit message.

**Comment by jech** [comment]
@MisterDA, I think you haven't been radical enough.

The `struct zone` stuff can go too — there is no need to retain this abstraction, which is only needed by disambiguation.  The function `chg_route` can go away too, it's just a wrapper around `change_route`.

As to the second commit, you forgot to remove `rule.c` and `rule.h`.

Feel free to squash the two commits together, I'll be happy to accept one big commit.

**Comment by MisterDA** [comment]
Thanks for the review, I think I’ve addressed all of your comments.

**Comment by jech** [comment]
What happens if we receive a source-specific IPv4 route?  `use_src` is true, then we speak to the kernel, and then all hell breaks loose?

What happens if we receive a source-specific rule on a kernel that doesn't support source-specific routing?

**Comment by MisterDA** [comment]
Hmm, there a lot that I haven’t considered. I think I’m not familiar enough with the code and the kernel history to address all the issues, I’m withdrawing this code. Thank you for your time.

**Comment by jech** [comment]
This is superseded by #65

**Pull request closed without merging**
