### PR TITLE
Makefile: automatic prerequisites and out-of-source build

### PR DESCRIPTION
**Pull request by MisterDA**
EDIT: see commit messages for description.

### CODE REVIEW

**Comment by MisterDA** [comment]
This is a work-in-progress, there are still a couple of issues I'd
like to work on.
- split the automatic prerequisites and out-of-source build (because
  oosb is important) into two commits;
- do something nice if the compiler doesn't support the automatic
  prerequisites flags;
- don't regenerate the version.h file every time.

**Comment by MisterDA** [comment]
I have addressed all my concerns and carefully checked compatibility
with GNU Make, BSD Make, GCC and Clang. My conclusions is that:
- this is an improvement;
- this will *almost never* break or change the current developer or
  packager workflows, *unless* then compiler does not support dependency
  flags, in which case they can be disabled (just like we disable -lrt
  on macOS);
- BSD Make does *not* support out-of-source builds;
- out-of-source builds are not enabled by default.

**Comment by MisterDA** [comment]
Nope, my bad, stuff is working by accident. BSD Make is the culprit.

**Comment by MisterDA** [comment]
The main problem is that BSD Make does not support pattern rules.
Now, by making explicit the implicit rules of GNU and BSD Make (they don't understand each other but cause no harm by reading each other), we can carefully craft rules to work with sub-directories and the future hmac branch.
The caveat is that for out-of-source build, the build path must end with a trailing slash: `make BUILD=build/`.
And everything works beautifully.

PS: GNU Make and BSD make really are different dialects. When you start rewriting implicit rules or having sub-directories, the Makefile ceases to be portable or needs to be generated or use arcane `VPATH` tricks.

PPS: after all, we aim for simplicity here. https://xkcd.com/1205/

**Comment by jech** [comment]
What problem is this trying to solve?

**Comment by MisterDA** [comment]
- out-of-source builds. Your build is constrained in a directory, which means that you can cross-compile or compile with different flags, and execute the different builds against each other. For instance, I usually do this with my raspberry pi for testing:

  ```
  branch="$(git rev-parse --abbrev-ref HEAD)"

  arch="$(cc -dumpmachine)"            
  build="build_$arch_$branch/"
  make BUILD="$build"

  (
    export PATH=../x-tools6h/arm-unknown-linux-gnueabihf/bin:$PATH
    build="build_$(cc -dumpmachine)_${branch}/"
    make BUILD="$build" &&
    scp "${build}babeld" "pi.ll:~/babeld_${branch}"
  )
  ```

  With that, I can have multiple builds of babeld for multiple architectures.
  When I can’t do out-of-source builds, I have to clean the whole build.

  For instance I used this technique to have two versions of babeld, one with the patch and one without to test the fix 7b79301 for #54.

  Sadly, implementing out-of-source builds could be way more easier if I could settle on a Makefile dialect and not on the intersection, or generate the Makefile. I think something prettier could be done with VPATH magic [1](https://www.gnu.org/software/automake/manual/html_node/VPATH-Builds.html) [2](https://www.gnu.org/software/make/manual/html_node/General-Search.html#General-Search). My fingers are itching. 
  Out-of-source is also meaningful when one doesn’t use a beefy computer, which was my case.

- automatic prerequisites. Note that the current Makefile does not declare dependencies on header files, which means that if you change something in a header and run make, make ignores the change. This has caught me by surprise at least once. As dependencies are a boring and cumbersome thing to write, and it’s easy to get them wrong, compiler have been generating them for us for quite some time.

- warnings. More kinds of warnings never hurt anyone. We’re absolutely not sinking under warnings reports here, and they’re a somewhat good indicator of code quality. They’ve helped me fix some bugs in my development code. Warning are not turned into errors, and won’t abort the compilation in any past, present, or future compiler.

Two last points: I believe that the patches will actually help new (unexperienced) developers, and the current workflow (by that, I mean `make && make install`) has not changed, and is not broken on {gcc, clang} × {gmake, bmake}, which is nice for packagers and respectable developers.

**Comment by MisterDA** [comment]
Here’s a much simpler implementation of the out-of-source commit
(8c2af42), which works with gmake and bmake :

``` diff
diff --git a/Makefile b/Makefile
index 43324ac..3cc7013 100644
--- a/Makefile
+++ b/Makefile
@@ -5,7 +5,7 @@ CDEBUGFLAGS = -Os -g -Wall
 
 DEFINES = $(PLATFORM_DEFINES)
 
-CFLAGS = $(CDEBUGFLAGS) $(DEFINES) $(EXTRA_DEFINES)
+CFLAGS = -I. $(CDEBUGFLAGS) $(DEFINES) $(EXTRA_DEFINES)
 
 LDLIBS = -lrt
 
@@ -25,7 +25,7 @@ local.o: local.c version.h
 kernel.o: kernel_netlink.c kernel_socket.c
 
 version.h:
-       ./generate-version.sh > $@
+       ./$(VPATH)/generate-version.sh > $@
 
 .SUFFIXES: .man .html
```

Then do:
```
# somewhere on your filesystem
# modern tools work like this
$ mkdir build && cd build
$ VATH=../path_to_babeld; make -f $VPATH/Makefile VPATH=$VPATH

# compared to my previous proposal
$ make BUILD=build_dir/
```

Do you prefer this? It reduces the noise in the Makefile.

The complete Makefile for the MAC branch may look like below. There
seem to be no other way than expliciting the default build rule if we
want to stay compatible between gmake and bmake.

``` diff
diff --git a/Makefile b/Makefile
index d8f5df9..819fb08 100644
--- a/Makefile
+++ b/Makefile
@@ -1,11 +1,14 @@
 PREFIX = /usr/local
 MANDIR = $(PREFIX)/share/man
 
+DEPFLAGS = -MMD -MP
+CPPFLAGS += $(DEPFLAGS)
+
 CDEBUGFLAGS = -Os -g -Wall
 
 DEFINES = $(PLATFORM_DEFINES)
 
-CFLAGS = $(CDEBUGFLAGS) $(DEFINES) $(EXTRA_DEFINES)
+CFLAGS = -I. $(CDEBUGFLAGS) $(DEFINES) $(EXTRA_DEFINES)
 
 LDLIBS = -lrt
 
@@ -14,22 +17,25 @@ SRCS = babeld.c net.c kernel.c util.c interface.c source.c neighbour.c \
        disambiguation.c rule.c mac.c \
        rfc6234/sha224-256.c BLAKE2/ref/blake2s-ref.c
 
-OBJS = babeld.o net.o kernel.o util.o interface.o source.o neighbour.o \
-       route.o xroute.o message.o resend.o configuration.o local.o \
-       disambiguation.o rule.o mac.o \
-       rfc6234/sha224-256.o BLAKE2/ref/blake2s-ref.o
+OBJS = $(SRCS:%.c=%.o)
+DEPS = $(SRCS:%.c=%.d)
 
 babeld: $(OBJS)
-       $(CC) $(CFLAGS) $(LDFLAGS) -o babeld $(OBJS) $(LDLIBS)
+       $(CC) $(LDFLAGS) -o $@ $(OBJS) $(LDLIBS)
+
+babeld.o: version.h
 
-babeld.o: babeld.c version.h
+local.o: version.h
 
-local.o: local.c version.h
+.SUFFIXES: .c .o
+.c.o:
+       @mkdir -p "$$(dirname "$@")"
+       $(CC) $(CPPFLAGS) $(CFLAGS) -o $@ -c $<
 
-kernel.o: kernel_netlink.c kernel_socket.c
+-include $(DEPS)
 
 version.h:
-       ./generate-version.sh > version.h
+       ./$(VPATH)/generate-version.sh > $@
 
 .SUFFIXES: .man .html
```
I think that this new version is better, I may force-push.

**Comment by MisterDA** [comment]
Here it is. Simpler?
Sorry for the force-pushes; I’m a bit tired.

**Comment by MisterDA** [comment]
Another thing that would be nice to have for the upcoming hmac branch is to automatically select the optimized routines for hmac-sha256 and blake2s. The two submodules contain optimized versions for neon and simd. The speed gains may be noticeable.
I don’t think this can easily be done without a meta build system (Autoconf, Meson, CMake, …). Or would a simple notice to the distro packager to change the path in the Makefile be enough?

**Comment by jech** [comment]
> The speed gains may be noticeable.

I doubt it.  I'd love to be proved wrong.

**Pull request closed without merging**
